-- 코드를 입력하세요
SELECT USER_ID, PRODUCT_ID 
FROM (
    SELECT USER_ID, PRODUCT_ID, COUNT(ONLINE_SALE_ID) AS cnt
    FROM ONLINE_SALE 
    GROUP BY USER_ID, PRODUCT_ID
    HAVING cnt > 1
) AS COUNT
ORDER BY USER_ID, PRODUCT_ID DESC


