-- 코드를 입력하세요
# SELECT FILTERED.REST_ID, FILTERED.REST_NAME, FILTERED.FOOD_TYPE, FILTERED.FAVORITES, FILTERED.ADDRESS, ROUND(AVG(REST_REVIEW.REVIEW_SCORE), 2) AS SCORE 
# FROM REST_REVIEW JOIN (
#     SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS
#     FROM REST_INFO
#     WHERE ADDRESS LIKE '서울%')
# ) AS FILTERED ON REST_REVIEW.REST_ID = FILTERED.REST_ID 
# GROUP BY REST_NAME
# ORDER BY SCORE DESC, FAVORITES DESC

# SELECT REST_INFO.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, AVG(REVIEW_SCORE) AS SCORE
# FROM REST_INFO JOIN REST_REVIEW ON REST_INFO.REST_ID 
# WHERE ADDRESS LIKE CONCAT("%", "서울", "%")
# GROUP BY REST_NAME
# ORDER BY SCORE DESC, FAVORITES DESC

SELECT 
    ri.REST_ID, 
    ri.REST_NAME, 
    ri.FOOD_TYPE, 
    ri.FAVORITES, 
    ri.ADDRESS, 
    ROUND(AVG(rr.REVIEW_SCORE), 2) AS AVG_SCORE
FROM 
    REST_INFO ri
JOIN 
    REST_REVIEW rr ON ri.REST_ID = rr.REST_ID
WHERE 
    ri.ADDRESS LIKE '서울%'
GROUP BY 
    ri.REST_ID, ri.REST_NAME, ri.FOOD_TYPE, ri.FAVORITES, ri.ADDRESS
ORDER BY 
    AVG_SCORE DESC, ri.FAVORITES DESC;
