-- 코드를 작성해주세요
SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS dev JOIN SKILLCODES skill ON dev.SKILL_CODE & skill.CODE > 0 
WHERE skill.NAME = "Python" OR skill.NAME = "C#"
ORDER BY ID ASC