-- 코드를 입력하세요
SELECT ii.FLAVOR
FROM (
    SELECT FLAVOR 
    FROM ICECREAM_INFO ii
    WHERE INGREDIENT_TYPE LIKE 'fruit_based'
) ii JOIN FIRST_HALF fh ON ii.FLAVOR = fh.FLAVOR
WHERE TOTAL_ORDER > 3000
ORDER BY TOTAL_ORDER DESC