-- 코드를 입력하세요
SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_CAR car
WHERE CAR_TYPE = "세단" 
    AND EXISTS (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY his
        WHERE car.CAR_ID = his.CAR_ID AND MONTH(START_DATE) = 10
    )
ORDER BY CAR_ID DESC